apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: auth-service-mysql
  labels:
    app: auth-service-mysql
spec:
  selector:
    matchLabels:
      app: auth-service-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-service-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: skaioskit
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: auth
          # TODO: use secrets
          #  valueFrom:
          #    secretKeyRef:
          #      name: mysql-pass
          #      key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: "${DIR}/working/mysql"
---
kind: Service
apiVersion: v1
metadata:
  name: auth-service-mysql
spec:
  selector:
    app: auth-service-mysql
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: localhost:5000/skaioskit/auth-service:latest
        imagePullPolicy: Always
        command: 
        - /auth
        - serve
        ports:
        - containerPort: 80
        env:
        - name: BUILD_DATETIME
          value: "${DATETIME}"
        volumeMounts:
        - name: log-storage
          mountPath: /logs
      volumes:
      - name: log-storage
        hostPath:
          path: "${DIR}/working/logs"
---
kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
---
